### PR TITLE
HP-496 Show verified personal information in admin

### PR DESCRIPTION
**Pull request by mikkokeskinen**
Adds VerifiedPersonalInformation model as a Stacked Inline admin in Profile admin. No user has permission to add, change, or delete the values.

Should we consider audit logging here?

### CODE REVIEW

**Review by akikoskinen — COMMENTED** [review]
Looks good so far. The verified personal information also contains three addresses (`permanent_address`, `temporary_address`, `permanent_foreign_address`). Those should be visible too.

**Comment by tkutinla** [comment]
As Aki already mentioned, "Verified personal information" as a concept includes also three addresses.

When it comes to audit logging,  discuss with Aki. We discussed about audit logging related to GraphQL queries and mutations of verified information, he knows what is missing from that. The same audit logging implementation (should) apply to both queries / mutations done through GraphQL and through Django-Admin.

**Comment by mikkokeskinen** [comment]
Ah. Didn't notice the addresses.

**Review by akikoskinen — APPROVED** [review]
Nice. Squash the last two commits together and it's ready to go.

**Pull request merged**
