### PR TITLE
Added Azure DevOps pipeline

### PR DESCRIPTION
**Pull request by Sukriva**
This pipeline extends the base pipeline and defines CI and PR triggers in GitHub

### CODE REVIEW

**Comment by akikoskinen** [comment]
I don't think this file should be in this repository as it refers private files in other repositories.

**Comment by Sukriva** [comment]
This file extends the pipeline that is in the azure repo.
Here is an example of the way it's supposed to work:
https://dev.azure.com/City-of-Helsinki/devops-toolchain/_git/devops-handbook?path=%2Fget-started-with-devops.md&_a=preview&anchor=pipeline-templates
And also the ticket for it:
https://helsinkiportaali.atlassian.net/browse/ADK-168

**Comment by akikoskinen** [comment]
> This file extends the pipeline that is in the azure repo.

Yes, this tries to extend a pipeline file. But you can't extend pipelines, only templates. 

> Here is an example of the way it's supposed to work:
> https://dev.azure.com/City-of-Helsinki/devops-toolchain/_git/devops-handbook?path=%2Fget-started-with-devops.md&_a=preview&anchor=pipeline-templates

This is a public open source repository. I don't quite like the idea that private hidden things are referenced from public files. I think another architecture needs to be considered.

> And also the ticket for it:
> https://helsinkiportaali.atlassian.net/browse/ADK-168

I have no access to see that. But I'm really interested on what it is that is the goal here. Apparently triggering some pipelines, I guess. But what pipelines? And on what triggers? Because for example, there's no usable pipeline for PRs yet, so what pipelines are tried to get triggered on PRs?

**Comment by jussiarpalahti** [comment]
@akikoskinen So, the idea here is get pipeline on Azure DevOps to trigger when commits happen in profile's repository. Actual pipeline does CI/CD elsewhere. Trigger or PRs is superfluous at the moment and could be removed. Pipeline decides over on Azure's side when to do its thing and when to ignore it (like for specific branches or tags).

Our deployment process isn't as public as our code, hence the private pipeline. Hopefully other methods arise for connecting Github and CI/CD. For now unfortunately files inside repositories is the only way...

**Comment by akikoskinen** [comment]
Ok. Perhaps we can have this kind of trigger file. I would suggest to name it to `helsinki-azure-pipelines.yml` or something like that to indicate that it's Helsinki specific.

Then a few other things:
- PR triggers shouldn't be used (yet), because there's no usable pipeline to handle those.
- `azure-pipelines.yml` in the private repo is on its way to get obsolete. There are replacing pipelines.
- There's already an automatic trigger in place (in Azure DevOps) that reacts on changes in `develop` branch.

...so what is the reason that this file is needed now, again? I don't think it brings anything that isn't already there currently.

Perhaps once there's a usable pipeline for PRs, we need this kind of file for triggering that pipeline.

**Comment by voneiden** [comment]
Closing this as spring cleanup of old stale PR's. 

We intend to do major rework on open-city-profile pipelines in the near future as part of a larger harmonization of different repository pipelines.

**Pull request closed without merging**
